### ISSUE TITLE
endpoint to dynamically generate JPEG file from stored TIFF

### ISSUE THREAD

**Issue by verbalhanglider** [uchicago-library/digcoll_retriever#5]
This endpoint should generate a jpeg file out of the stored TIFF file on-the-fly.

Potential problems:
 - processing power requirements for this to be done at scale 
 - what assurances are there that TIFF files are named correctly? what is the level of assurance?

Advantages
 - reduced storage requirement for a particular collection
 - greater control over JPEGs generated for interface viability

**Comment by bnbalsamo** [comment]
https://github.com/uchicago-library/digcoll_retriever/commit/caf63503d1d6f87445dde29dff4558bf51597907 pretty much takes care of this.

Closing the issue
